Added Player HUD
justalemon/GGOV pull request #10
Opened 2018-10-10 18:03 UTC by NamStalker

Added the player HUD with player information, health bar, main and side arms with ammo counters. Refactored to reduce size of the mod, and reduce some of the calculations. Added Weapons class to handle weapon properties and resources. Updated the common.json to reflect resolution changes, this was discovered as I use a 4k monitor, and realized setting the game to 1920x1080 was the only way to get the display working initially.

2018-10-10 23:14 UTC, NamStalker commented
issues #3

2018-10-11 02:34 UTC, justalemon requested changes
I have not tested it yet, but a change needs to be made

2018-10-11 02:34 UTC, justalemon commented on GGO.Common/Draw.cs
> +            if(Character.IsAlive)
2 things:
* There should be an space after the word if.
* {} Should be used

2018-10-11 02:34 UTC, justalemon commented on GGO.Common/Draw.cs
> +                if(!(Weapons.CurrentWeaponType == Weapons.Type.Melee && isOffHand))
Same here

2018-10-11 03:05 UTC, NamStalker commented on GGO.Common/Draw.cs
> +                if(!(Weapons.CurrentWeaponType == Weapons.Type.Melee && isOffHand))
Changes have been made.

2018-10-12 11:29 UTC, justalemon approved these changes

2018-10-12 11:29 UTC, merged